name:                echobot
version:             0.1.0.0
github:              "alexd1971/echobot"
license:             BSD3
author:              "Aleksey Danilevsky"
maintainer:          "alexey.danilevsky@gmail.com"
copyright:           "2021 Aleksey Danilevsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/echobot#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- generic-random
- unordered-containers
- hspec
- QuickCheck
- text
- yaml

library:
  source-dirs: src

executables:
  echobot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echobot

tests:
  types-test:
    main:                TypesTest.hs
    source-dirs:         test/types
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echobot
  config-test:
    main:                Main.hs
    source-dirs:         test/bot_config
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echobot
